// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DivisionControlUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcDivisionControlUnit {

  /// <summary>Holder for reflection information generated from DivisionControlUnit.proto</summary>
  public static partial class DivisionControlUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for DivisionControlUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DivisionControlUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlEaXZpc2lvbkNvbnRyb2xVbml0LnByb3RvEhdHcnBjRGl2aXNpb25Db250",
            "cm9sVW5pdCJUChxSZWdpc3RlckFydGlsbGVyeVVuaXRSZXF1ZXN0Eg8KB3Vu",
            "aXRfaWQYASABKAkSEQoJbG9uZ2l0dWRlGAIgASgFEhAKCGxhdGl0dWRlGAMg",
            "ASgFIjAKHVJlZ2lzdGVyQXJ0aWxsZXJ5VW5pdFJlc3BvbnNlEg8KB21lc3Nh",
            "Z2UYASABKAkylAEKE0RpdmlzaW9uQ29udHJvbFVuaXQSfQoMUmVnaXN0ZXJV",
            "bml0EjUuR3JwY0RpdmlzaW9uQ29udHJvbFVuaXQuUmVnaXN0ZXJBcnRpbGxl",
            "cnlVbml0UmVxdWVzdBo2LkdycGNEaXZpc2lvbkNvbnRyb2xVbml0LlJlZ2lz",
            "dGVyQXJ0aWxsZXJ5VW5pdFJlc3BvbnNlQhqqAhdHcnBjRGl2aXNpb25Db250",
            "cm9sVW5pdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcDivisionControlUnit.RegisterArtilleryUnitRequest), global::GrpcDivisionControlUnit.RegisterArtilleryUnitRequest.Parser, new[]{ "UnitId", "Longitude", "Latitude" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcDivisionControlUnit.RegisterArtilleryUnitResponse), global::GrpcDivisionControlUnit.RegisterArtilleryUnitResponse.Parser, new[]{ "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegisterArtilleryUnitRequest : pb::IMessage<RegisterArtilleryUnitRequest> {
    private static readonly pb::MessageParser<RegisterArtilleryUnitRequest> _parser = new pb::MessageParser<RegisterArtilleryUnitRequest>(() => new RegisterArtilleryUnitRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterArtilleryUnitRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcDivisionControlUnit.DivisionControlUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitRequest(RegisterArtilleryUnitRequest other) : this() {
      unitId_ = other.unitId_;
      longitude_ = other.longitude_;
      latitude_ = other.latitude_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitRequest Clone() {
      return new RegisterArtilleryUnitRequest(this);
    }

    /// <summary>Field number for the "unit_id" field.</summary>
    public const int UnitIdFieldNumber = 1;
    private string unitId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UnitId {
      get { return unitId_; }
      set {
        unitId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 2;
    private int longitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 3;
    private int latitude_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterArtilleryUnitRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterArtilleryUnitRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnitId != other.UnitId) return false;
      if (Longitude != other.Longitude) return false;
      if (Latitude != other.Latitude) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnitId.Length != 0) hash ^= UnitId.GetHashCode();
      if (Longitude != 0) hash ^= Longitude.GetHashCode();
      if (Latitude != 0) hash ^= Latitude.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnitId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UnitId);
      }
      if (Longitude != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Longitude);
      }
      if (Latitude != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Latitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnitId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UnitId);
      }
      if (Longitude != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Longitude);
      }
      if (Latitude != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Latitude);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterArtilleryUnitRequest other) {
      if (other == null) {
        return;
      }
      if (other.UnitId.Length != 0) {
        UnitId = other.UnitId;
      }
      if (other.Longitude != 0) {
        Longitude = other.Longitude;
      }
      if (other.Latitude != 0) {
        Latitude = other.Latitude;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UnitId = input.ReadString();
            break;
          }
          case 16: {
            Longitude = input.ReadInt32();
            break;
          }
          case 24: {
            Latitude = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RegisterArtilleryUnitResponse : pb::IMessage<RegisterArtilleryUnitResponse> {
    private static readonly pb::MessageParser<RegisterArtilleryUnitResponse> _parser = new pb::MessageParser<RegisterArtilleryUnitResponse>(() => new RegisterArtilleryUnitResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterArtilleryUnitResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcDivisionControlUnit.DivisionControlUnitReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitResponse(RegisterArtilleryUnitResponse other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterArtilleryUnitResponse Clone() {
      return new RegisterArtilleryUnitResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterArtilleryUnitResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterArtilleryUnitResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterArtilleryUnitResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
